#!/usr/bin/env node

// Starts a daemon process to listen to all relayed messages.
const networks = require('../networks.json').networks;
const spawn = require('child_process').spawn;
const fs = require('fs');

const logF = `${process.cwd()}/daemon.log`;
const errorF = `${process.cwd()}/daemon.error.log`;
if(fs.existsSync(logF)) { fs.unlinkSync(logF); };
if(fs.existsSync(errorF)) { fs.unlinkSync(errorF); };

const access = fs.createWriteStream('./daemon.log', { flags: 'a' });
const error = fs.createWriteStream('./daemon.error.log', { flags: 'a' });

const hosts = [];
Object.keys(networks).forEach((n) => {
  hosts.push([networks[n].wsProvider, networks[n].gateway, networks[n].value]);
})

let processes = {};
hosts.forEach((host) => {
  listenSubProcess(host);
})


// Start a subprocess to listen on a host
function listenSubProcess(host) {
  const daemon = spawn(`./daemon/daemon`, host,
    { stdio: ['pipe', 'pipe', 'pipe', 'ipc'] })
  // Keep the process in a store for messaging
  processes[host[2].toLowerCase()] = daemon;
  daemon.stdout.pipe(access);
  daemon.stderr.pipe(error);
  daemon.on('close', () => {
    setTimeout(() => {
      console.log(new Date(), 'Process terminated listening to', host);
      listenSubProcess(host);
    }, 1000);
  })

  // Every message is of form: { to, from, body }
  daemon.on('message', (message) => {
    processes[message.to.toLowerCase()].send(message);
  })
}
